io.r2dbc.spi.R2dbcBadGrammarException: Incorrect datetime value: '+643696-06-04 17:33:42' for column `goplanV1`.`accident_history`.`ah_accident_time` at row 1

{
  "accident_time": 20250930040422,
  "call_id": "C000000009260234",
  "claim_number": "20250930040422",
  "claim_time": 20250930040422,
  "proxy_driv_coorp_cmpcd": "G02"
}
